export const SampleQuery = "";
export const loginUserQuery = "SELECT * FROM users where email = ?";
export const signUpUserQuery = "INSERT INTO users(name, email, password, userStatus) values(?, ?, ?, ?)"; 
export const selectProjectById = "SELECT * FROM projects WHERE projectId = ?";  
export const selectUserById = "SELECT * FROM users WHERE userId = ?";
export const selectUserByEmail = "SELECT * FROM users where email = ?";
export const saveNewPage = "INSERT INTO pages(projectId, pageName, description, data, isPublished, lastModified) values(?, ?, ?, ?, ?, ?)";
export const saveNewComponent = "INSERT INTO components(userId, icon, componentName, data, lastModified) values(?, ?, ?, ?, ?)";
export const saveNewProject = "INSERT INTO projects(userId, projectName, description, isPublished) values(?, ?, ?, ?)";
export const selectProjectByUserId = "SELECT * FROM projects where userId = ?"; 
export const getUserPagesQuery = "SELECT * FROM projects LEFT JOIN pages ON pages.projectId = projects.projectId WHERE projects.userId = ?";
export const getUserComponentsQuery = "SELECT * FROM components WHERE userId = ?";
export const deleteProjectQuery = "DELETE FROM projects WHERE projectId = ?";
export const deletePageQuery = "DELETE FROM pages WHERE projectId = ?";
export const deleteCustomComponentQuery = "DELETE FROM components WHERE userId = ? and id = ?";
export const deleteAllCustomComponentsQuery = "DELETE FROM components WHERE userId = ?";